server:
  port: 2017
spring:
  datasource:
    url: jdbc:mysql://192.168.2.21:3306/scrs_db?characterEncoding=utf8&useSSL=false #本地测试库
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming:
        #对SQL大小写进行控制
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  freemarker:
    content-type: text/html
    prefer-file-system-access: false
    settings:
      locale: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##  #防止ID被格式化加逗号
      auto_import: /spring.ftl as spring
  messages:
    basename: i18n/messages
  redis:
    database: 40 # Redis数据库索引40
    host: 192.168.0.39 # Redis服务器地址
    port: 15818  # Redis服务器连接端口
    password: Redis1231123@#@!!=-23Sdasd1231gjoiuq123#@sda2131-sadas213dsada@#^%&13asdad3412452332
logging:
  level:
    com.daqsoft.mapper: debug
 # file: log.log
com:
  daqsoft:
    framework:
      title: 数字景区综合管控平台  #项目名
      cache-entity-time-out: 100 #缓存超时时间(分钟)
      min-region:  650100
      oauth2:
        client:
#          client-id: client
#          client-secret: secret
          client-id: 73592c5c8b934430becfd33cdcc5ec87
          client-secret: 5ed10325c48e4d0493690fcebedb4fc9
          access-token-uri: http://192.168.2.90:9091/oauth/token
          user-authorization-uri: http://192.168.2.90:9091/oauth/authorize
          authorization-logout-url: http://192.168.2.90:9091/logout
          token-name: oauth_token
          authentication-scheme: query
          client-authentication-scheme: form
        resource:
          token-info-uri: http://192.168.2.90:9091/oauth/check_token
          user-info-uri: http://192.168.2.90:9091/u
      index-url-location: /scrsIndex/list
      user-subordination-display: false
      allow-from-strategy: http://192.168.2.90:9091
      ignore-paths: /rest/**

mybatis:
#  typeAliasesPackage: com.daqsoft.entity
  mapper-locations: classpath:mapper/resource/*.xml,mapper/control/*.xml,mapper/common/*.xml,mapper/app/*.xml
  logImpl: STDOUT_LOGGING

